FROM ubuntu

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get -y install curl
RUN apt-get -y install gnupg
RUN apt-get -y install vim
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt -y install nodejs
RUN node -v
RUN npm -v

COPY cinema-review-admin /usr/src/cinema-review-admin/
RUN cd /usr/src/cinema-review-admin/ && npm install

CMD ["node", "/usr/src/cinema-review-admin/index.js"]

EXPOSE 5000
